databases:
  - name: poker
    databaseName: poker
    user: poker

services:
  - type: web
    name: poker
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne poker.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poker
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.2
