# Generated by Django 5.0.4 on 2024-04-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("poker", "0005_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokersession",
            name="auto_reveal",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="pokersession",
            name="deck",
            field=models.CharField(
                choices=[("reach", "Reach"), ("tshirt", "T-shirt"), ("fibonacci", "Fibonacci"), ("months", "Months")],
                default="tshirt",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("event", models.CharField(max_length=100)),
                ("data", models.JSONField(default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="logs", to="poker.pokersession"
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
    ]
